<?php

/**
 * Created by IntelliJ IDEA.
 * User: Administrator
 * Date: 2018/5/10
 * Time: 14:57
 */
require_once 'People.php';

class Man extends People
{
    public function __construct( $age,  $name)
    {
        parent::__construct($age, $name, '男');
    }

    public function hi()
    {
        parent::hi(); // TODO: Change the autogenerated stub

        echo '<br>Man '.$this->getName().'say hi';
    }
}